export const actionTypes = {
    RENT_REQUESTS_PENDING: "RENT_REQUESTS_PENDING",
    RENT_REQUESTS_SUCCESS: "RENT_REQUESTS_SUCCESS",
    RENT_REQUESTS_ERROR: "RENT_REQUESTS_ERROR",

    RENT_ANNOUNCEMENT_PENDING: "RENT_ANNOUNCEMENT_PENDING",
    RENT_ANNOUNCEMENT_SUCCESS: "RENT_ANNOUNCEMENT_SUCCESS",
    RENT_ANNOUNCEMENT_ERROR: "RENT_ANNOUNCEMENT_ERROR",

    RENT_ANNOUNCEMENT_CREATE_PENDING: "RENT_ANNOUNCEMENT_CREATE_PENDING",
    RENT_ANNOUNCEMENT_CREATE_SUCCESS: "RENT_ANNOUNCEMENT_CREATE_SUCCESS",
    RENT_ANNOUNCEMENT_CREATE_ERROR: "RENT_ANNOUNCEMENT_CREATE_ERROR",

    RENT_REQUEST_CREATE_PENDING: "RENT_REQUEST_CREATE_PENDING",
    RENT_REQUEST_CREATE_SUCCESS: "RENT_REQUEST_CREATE_SUCCESS",
    RENT_REQUEST_CREATE_ERROR: "RENT_REQUEST_CREATE_ERROR",
  };

  //rental