export const actionTypes = {
    RENT_REQUESTS_PENDING: "RENT_REQUESTS_PENDING",
    RENT_REQUESTS_SUCCESS: "RENT_REQUESTS_SUCCESS",
    RENT_REQUESTS_ERROR: "RENT_REQUESTS_ERROR",

    RENT_ANNOUNCEMENT_PENDING: "RENT_ANNOUNCEMENT_PENDING",
    RENT_ANNOUNCEMENT_SUCCESS: "RENT_ANNOUNCEMENT_SUCCESS",
    RENT_ANNOUNCEMENT_ERROR: "RENT_ANNOUNCEMENT_ERROR",

    RENT_ANNOUNCEMENT_INFO_PENDING: "RENT_ANNOUNCEMENT_INFO_PENDING",
    RENT_ANNOUNCEMENT_INFO_SUCCESS: "RENT_ANNOUNCEMENT_INFO_SUCCESS",
    RENT_ANNOUNCEMENT_INFO_ERROR: "RENT_ANNOUNCEMENT_INFO_ERROR",

    RENT_ANNOUNCEMENT_CREATE_PENDING: "RENT_ANNOUNCEMENT_CREATE_PENDING",
    RENT_ANNOUNCEMENT_CREATE_SUCCESS: "RENT_ANNOUNCEMENT_CREATE_SUCCESS",
    RENT_ANNOUNCEMENT_CREATE_ERROR: "RENT_ANNOUNCEMENT_CREATE_ERROR",

    RENT_REQUEST_CREATE_PENDING: "RENT_REQUEST_CREATE_PENDING",
    RENT_REQUEST_CREATE_SUCCESS: "RENT_REQUEST_CREATE_SUCCESS",
    RENT_REQUEST_CREATE_ERROR: "RENT_REQUEST_CREATE_ERROR",

    PAGE_NUMBER_CHANGED: "PAGE_NUMBER_CHANGED",

    
    UPDATE_FILTERS: "UPDATE_FILTERS",
  };

  //rental