export const actionTypes = {
    AUTHORIZATION_PENDING: "AUTHORIZATION_PENDING",
    AUTHORIZATION_SUCCESS: "AUTHORIZATION_SUCCESS",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",

    LOGOUT_ERROR: "LOGOUT_ERROR",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  };