export const actionTypes = {
    AUTHORIZATION_PENDING: "AUTHORIZATION_PENDING",
    AUTHORIZATION_SUCCESS: "AUTHORIZATION_SUCCESS",
    AUTHORIZATION_ERROR: "AUTHORIZATION_ERROR",

    LOGOUT: "LOGOUT",

    USER_INFO_PENDING: "USER_INFO_PENDING",
    USER_INFO_SUCCESS: "USER_INFO_SUCCESS",
    USER_INFO_ERROR: "USER_INFO_ERROR",
  };