export const actionTypes = {

    USER_REQUESTS_PENDING: "USER_REQUESTS_PENDING",
    USER_REQUESTS_SUCCESS: "USER_REQUESTS_SUCCESS",
    USER_REQUESTS_ERROR: "USER_REQUESTS_ERROR",

    USER_ANNOUNCEMENT_PENDING: "USER_ANNOUNCEMENT_PENDING",
    USER_ANNOUNCEMENT_SUCCESS: "USER_ANNOUNCEMENT_SUCCESS",
    USER_ANNOUNCEMENT_ERROR: "USER_ANNOUNCEMENT_ERROR",

    USER_RESERVATION_PENDING: "USER_RESERVATION_PENDING",
    USER_RESERVATION_SUCCESS: "USER_RESERVATION_SUCCESS",
    USER_RESERVATION_ERROR: "USER_RESERVATION_ERROR",

    RENT_REQUESTS_DELETE_PENDING: "RENT_REQUESTS_DELETE_PENDING",
    RENT_REQUESTS_DELETE_SUCCESS: "RENT_REQUESTS_DELETE_SUCCESS",
    RENT_REQUESTS_DELETE_ERROR: "RENT_REQUESTS_DELETE_ERROR",

    RENT_ANNOUNCEMENT_DELETE_PENDING: "RENT_ANNOUNCEMENT_DELETE_PENDING",
    RENT_ANNOUNCEMENT_DELETE_SUCCESS: "RENT_ANNOUNCEMENT_DELETE_SUCCESS",
    RENT_ANNOUNCEMENT_DELETE_ERROR: "RENT_ANNOUNCEMENT_DELETE_ERROR",

    RESERVATION_CREATE_PENDING: "RESERVATION_CREATE_PENDING",
    RESERVATION_CREATE_SUCCESS: "RESERVATION_CREATE_SUCCESS",
    RESERVATION_CREATE_ERROR: "RESERVATION_CREATE_ERROR",

    RESERVATION_ACCEPT_PENDING: "RESERVATION_ACCEPT_PENDING",
    RESERVATION_ACCEPT_SUCCESS: "RESERVATION_ACCEPT_SUCCESS",
    RESERVATION_ACCEPT_ERROR: "RESERVATION_ACCEPT_ERROR",
    
    RESERVATION_REJECT_PENDING: "RESERVATION_REJECT_PENDING",
    RESERVATION_REJECT_SUCCESS: "RESERVATION_REJECT_SUCCESS",
    RESERVATION_REJECT_ERROR: "RESERVATION_REJECT_ERROR",

    RESERVATION_COMPLETE_PENDING: "RESERVATION_COMPLETE_PENDING",
    RESERVATION_COMPLETE_SUCCESS: "RESERVATION_COMPLETET_SUCCESS",
    RESERVATION_COMPLETE_ERROR: "RESERVATION_COMPLETE_ERROR",
  };
